# ====== Server ======
server.port=8085

# ====== DataSource (H2 pour le dev) ======
spring.datasource.url=jdbc:h2:mem:bank-db
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ====== JPA ======
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ====== Application ======
spring.application.name=digital-banking

# ====== Swagger ======
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=ma.enset.digitalbanking.web